### ISSUE TITLE
Deploy updated version to php.microformats.io

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/mf2-parser-website#10]
@veganstraightedge do you know how to update the Heroku site? I thought this repo was configured with a deploy hook but it doesn't seem to be working.

**Comment by veganstraightedge** [comment]
Looks like I can't setup auto deploys for repos that I don't own or aren't in orgs that I'm a part of.

If you moved this repo to /indieweb (and say, renamed it to `microformats-parser-website-php`), I could hookup the auto deploy on Heroku.

**Comment by veganstraightedge** [comment]
In the meantime, I just manually pulled from GitHub and pushed to Heroku

**Comment by veganstraightedge** [comment]
Auto deploys are set up and working now.

All commits to `master` get deployed to `php.microformats.io`
